### ISSUE TITLE
Unexpected gpu-id behaviours

### ISSUE THREAD

**Issue by mathieuboudreau** [ivadomed/ivadomed#1208]
## Issue description

**Full disclosure: I discovered these while reviewing a PR for AxonDeepSeg ([PR# 701](https://github.com/axondeepseg/axondeepseg/pull/701)), so I've only tested it with the settings/API that @mariehbourget used to implement that functionality there**

### Current behavior

When selecting a gpu-id other than 0 (eg. 5), memory is allocated to gpu-id 0 regardless, and it does so both prior and during the use of the given gpu-id (eg. 5).

Also, if `CUDA_VISIBLE_DEVICES` is set for the session to something other than starting from 0 (eg `CUDA_VISIBLE_DEVICES=3,4,5`, then gpu-id does not set the device number that is set, but is in fact the ID relative to the visible devices (eg for `CUDA_VISIBLE_DEVICES=3,4,5`, a gpu-id of 1 (remember that in python, count starts at 0), the gpu device that would be set would be the gpu-id 4, and not 1.

### Expected behavior
 

Only the selected gpu-id should have memory used.

gpu-id documentation should also reflect how it behaves with CUDA_VISIBLE_DEVICES values set.

### Steps to reproduce

While testing our PR, I would set the gpu-id to 5 through the ADS/IVADOMED API, but noticed while monitoring the the `nvidia-smi` that the GPU ID would get some memory allocated in addition, and it would start before the memory started being used in the ID I set to 5.

<img width="566" alt="Screenshot 2022-11-25 at 3 30 58 PM" src="https://user-images.githubusercontent.com/1421029/204045299-fb162031-70ee-4881-beb5-44aa5ed9098d.png">

Command: `axondeepseg -t SEM -i AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/image.png --gpu-id 5`

Looking online, some commentators say that it's because when pytorch "turns on", it automatically initializes the CUDA device using device 0 (but more on that later): https://github.com/pytorch/pytorch/issues/2383#issuecomment-323112926

People in another suggested using CUDA_VISIBLE_DEVICES so that the device 0 isn't used.

Trying this, I discovered the second behaviour bug.

Command: `CUDA_VISIBLE_DEVICES=5,6 axondeepseg -t SEM -i AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/image.png --gpu-id 5`

<img width="1007" alt="Screenshot 2022-11-25 at 3 23 21 PM" src="https://user-images.githubusercontent.com/1421029/204044522-cbaa3163-0088-46ed-82e5-7dd35af7bac9.png">

The code now errors.

This is because the gpu-id (as now implemented in IVADOMED) is in fact not the ID of the GPU, but instead the ID relative to the visible devices: https://discuss.pytorch.org/t/runtimeerror-cuda-error-invalid-device-ordinal/67488

So changing it to 

Command: `CUDA_VISIBLE_DEVICES=5,6 axondeepseg -t SEM -i AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/image.png --gpu-id 0`

Now works:

<img width="566" alt="Screenshot 2022-11-25 at 3 25 23 PM" src="https://user-images.githubusercontent.com/1421029/204044740-7dda9b48-e580-40b6-9f4f-ba377c04d34a.png">

**However**, note that if the list visible devices **don't** begin with the device I want to use, then the first visible device will still have some memory used from the point earlier on, it's not **always** device 0 that has memory taken to boot up pytorch (and to this point, I don't know where and if this can be stopped/changed), but it's the **first** in the list of available devices that this will occur for, for example:

Command: `CUDA_VISIBLE_DEVICES=1,3,5,7 axondeepseg -t SEM -i AxonDeepSeg/models/model_seg_rat_axon-myelin_sem/data_test/image.png --gpu-id 2`

Will result in:

<img width="566" alt="Screenshot 2022-11-25 at 3 28 20 PM" src="https://user-images.githubusercontent.com/1421029/204045032-964dc7ac-750b-4efa-b5cf-341e5daa8691.png">

I thought you should all be aware of these behaviours, as I've looked at your documentation and didn't see these details noted.

I've also shown all of this to @mariehbourget on Zoom, so if anything isn't well explained, hopefully she can clarify to you.

## Environment

See the AxonDeepSeg PR linked above.

### System description
`rosenberg` machine at Poly.

### Installed packages

See the AxonDeepSeg PR linked above.

**Comment by mariehbourget** [comment]
Thanks @mathieuboudreau for reporting this issue and for the description.

I have the beginning of an answer and some potential solutions.
This is a new topic for me, so my explanations and analogies may not always be correct 😅.

For simplicity, I will only address the first part of your question which was:
> When selecting a gpu-id other than 0 (eg. 5), memory is allocated to gpu-id 0 regardless, and it does so both prior and during the use of the given gpu-id (eg. 5).

### Reproducing the issue in ivadomed
* I tried reproducing the issue when using ivadomed with the command `--segment`. However, I do not have the same issue as with the `segment_volume` API in ADS, i.e. only the gpu-id from the config file is used, as expected.
* This means that somewhere in `main.py`, ivadomed already has "set" the correct gpu and somewhat "remembers" it when using `segment_volume`.
* This is what I found:
    * In `main.py`, the gpu device is "set" from the config file before going into the `run_segment_command` and the `segment_volume` function here: https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/main.py#L375
    * Then in `segment_volume`, the pytorch DataLoader "remembers" the correct gpu with the option `pin_memory=True` here: https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/inference.py#L487-L490
    * Then in `get_preds` the "correct" gpu-id is used both for ivadomed and ADS (this is why we see 2 gpu in use with ADS: GPU 0 is from the DataLoader in `segment_volume`, and GPU 5 is from the `get_preds` function) https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/inference.py#L48-L62 

### How can we fix it in the segment_volume API?
Here are some preliminary ideas, we would have to evaluate their impact on both ivadomed and SCT (as SCT uses also `segment_volume` but not the gpu-id options AFAIK).

* We could add the `cuda_available, device = imed_utils.define_device(gpu_id)` in `segment_volume` in addition or instead of the one in `get_preds`.
* We could set the `pin_memory` argument to `False`.

### But can we fix it directly in ADS?

Turns out we could. It work if we:
* import imed_utils: `from ivadomed import utils  as imed_utils`) in `apply_model.py`.
*  "set" the device with the same line (`cuda_available, device = imed_utils.define_device(gpu_id)`) in ADS in `apply_model.py` [here](https://github.com/axondeepseg/axondeepseg/blob/3fc7c4d379c92500e88ecdb8983129d77e395dd9/AxonDeepSeg/apply_model.py#L51) before calling `segment_volume`.
* We could also write our own method to "set" the device without importing the method from ivadomed. In any case, we need to import torch on one side or another to set the device.

### Next steps

* I don't know which one of these options would be the best practice to set the GPU for ADS, maybe @dyt811 has some insights?
* I would be in favor of "setting" the device in ADS and writing our own function because we will eventually need to import torch anyway to count the number of GPU available (as discussed in ADS meeting).
* I suggest we clarify this before addressing the second part of the question about the documentation of `CUDA_VISIBLE_DEVICES`.

Note: all the potential solutions are compatible with CPU segmentation.

**Comment by dyt811** [comment]
Fix upstream is probably better in Ivadomed. 
Being more explicit is better than implicit would be my guess. So probably updating `segment_volume` with the `define_device` would be my guess base on what I understood.

**Comment by kanishk16** [comment]
Thanks @mathieuboudreau, for uncovering this bug and the extensive details.

@mariehbourget There might be more than a single issue to be addressed but let's start with one at a time.
> ### Reproducing the issue in ivadomed
> * I tried reproducing the issue when using ivadomed with the command `--segment`. However, I do not have the same issue as with the `segment_volume` API in ADS, i.e. only the gpu-id from the config file is used, as expected.
> * This means that somewhere in `main.py`, ivadomed already has "set" the correct gpu and somewhat "remembers" it when using `segment_volume`.
> * This is what I found:
>   
>   * In `main.py`, the gpu device is "set" from the config file before going into the `run_segment_command` and the `segment_volume` function here: https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/main.py#L375
>   * Then in `segment_volume`, the pytorch DataLoader "remembers" the correct gpu with the option `pin_memory=True` here: https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/inference.py#L487-L490
>   * Then in `get_preds` the "correct" gpu-id is used both for ivadomed and ADS (this is why we see 2 gpu in use with ADS: GPU 0 is from the DataLoader in `segment_volume`, and GPU 5 is from the `get_preds` function) https://github.com/ivadomed/ivadomed/blob/1e8a6bda2b41761c04b3a1cbc1d9b49ec9ee884b/ivadomed/inference.py#L48-L62

Since the `dataloader` doesn't utilize GPU (might be wrong but assuming this is correct for now) and there is as suggested by you nothing wrong with `get_preds`. This essentially means as discussed in the meeting, somewhere after the call to the `dataloader` and before the call to `get_preds` another GPU is set in the global space and looks like https://github.com/ivadomed/ivadomed/blob/5b2e313154e94bbcc350ab56be7adf10f3d089c4/ivadomed/utils.py#L165 should be blamed for it. I'm curious to know the behavior when we comment out this line particularly because the docs [discourage its use](https://pytorch.org/docs/master/generated/torch.cuda.set_device.html#torch.cuda.set_device) and it might lead to the above behaviours (will link to the issue shortly)

**Comment by mariehbourget** [comment]
Thanks @dyt811, @kanishk16 and @naga-karthik for your insights on this issue.

As discussed in meeting:
* We want to keep pin_memory=true because it speed-up the transfer between CPU and GPU (ref).
* We agreed that any fix should be done in ivadomed, probably in `segment_volume` as it is 1 of the 4 entry points of ivadomed. (The others are commands -`-train`, `--test` and `--segment` for which the device is defined in the main)
* So an easy fix would be to call `cuda_available, device = imed_utils.define_device(gpu_id)` in `segment_volume` instead of `get_preds`.




> Since the `dataloader` doesn't utilize GPU (might be wrong but assuming this is correct for now) and there is as suggested by you nothing wrong with `get_preds`.

I tested again and confirm that `get_preds` is the part that works as expected by using only the `gpu_id` passed to `segment_volume`.
GPU 0 is used [between lines 487 and 495](https://github.com/ivadomed/ivadomed/blob/5b2e313154e94bbcc350ab56be7adf10f3d089c4/ivadomed/inference.py#L487-L495) just before `get_preds`.
So somehow, the DataLoader, or transfer from CPU to GPU is using the GPU 0 when `pin_memory=True`. When `pin_memory=False`, this issue does not happen.


>This essentially means as discussed in the meeting, somewhere after the call to the `dataloader` and before the call to `get_preds` another GPU is set in the global space and looks like
> 
> https://github.com/ivadomed/ivadomed/blob/5b2e313154e94bbcc350ab56be7adf10f3d089c4/ivadomed/utils.py#L165
> 
> should be blamed for it. I'm curious to know the behavior when we comment out this line particularly because the docs [discourage its use](https://pytorch.org/docs/master/generated/torch.cuda.set_device.html#torch.cuda.set_device) and it might lead to the above behaviours (will link to the issue shortly)

Interesting!
So `torch.cuda.set_device(gpu_id)` is in the [define_device](https://github.com/ivadomed/ivadomed/blob/5b2e313154e94bbcc350ab56be7adf10f3d089c4/ivadomed/utils.py#L147) function which is precisely the function used both in main.py and in get_preds to "set" the GPU.
I don't think it is to blame since it seems to be the part that works (in main an in get_preds).

As for the usage of CUDA_VISIBLE_DEVICES environment variable, we have to make sure that this could be compatible with the usage of `segment_volume` from outside ivadomed (ADS, SCT).

**Comment by mathieuboudreau** [comment]
Thank you all for your thorough investigations into this issue and your work towards resolving it 🙏

**Comment by mariehbourget** [comment]
I did some research on the different ideas discussed so far with @kanishk16 :

1. Using `torch.cuda.device` instead of the discouraged `torch.cuda.set_device`:
As far as I understand from [this](https://github.com/pytorch/pytorch/issues/1608#issuecomment-303020201), `torch.cuda.device` is a context manager to use a specific device, so it has to be used as
```
with torch.cuda.device('gpu_id'):
    do something
```
It works well with our code when we use GPU but I was not able to make it work with CPU without having an if/else based on cuda availability. This would still be feasible but I find that it complicates the code and doesn't see any real benefit compare to `set_device` (as we do currently).

2. Using `CUDA_VISIBLE_DEVICES`:
I'm not a fan of this solution because it has to be defined as an environment variable before launching ivadomed (or ADS) from the CLI. So it wouldn't be very user friendly, especially when calling ivadomed from ADS and it would also duplicate the functionality of our `gpu_id` config parameter.

3. Using `define_device` in `segment_volume`:
This is my favorite solution and I was able to implement it in #1209.
It works for both CPU and GPU, in ivadomed and in ADS.

Let me know your thoughts, thanks!

**Comment by kanishk16** [comment]
On a surface level, it appears `pin_memory=True` has [no effect on GPU memory](https://discuss.pytorch.org/t/when-to-set-pin-memory-to-true/19723/2) but after perusing a few issues and docs it does have an effect on GPU memory. The confusion arose due to the [post1](https://discuss.pytorch.org/t/when-to-set-pin-memory-to-true/19723/2) and [post2](https://discuss.pytorch.org/t/pin-memory-to-specific-gpu-in-dataloader/11908) on PyTorch Forum but the [official docs](https://pytorch.org/docs/1.12/data.html#torch.utils.data.DataLoader) clear out everything. Moreover, PyTorch 1.12 onwards there's a parameter (`pin_memory_device`) to specify the GPU that would be utilized by the dataloader in case of a multi-GPU scenario. Looking at [MONAI](https://docs.monai.io/en/0.2.0/_modules/monai/data/dataloader.html) same can be inferred.

Thanks @mariehbourget for empirically validating this, as I was always under the assumption data loader does not influence GPU memory irrespective of `pin_memory` being `True` or `False`.

> 3. Using `define_device` in `segment_volume`:
>    This is my favorite solution and I was able to implement it in [Fix GPU behavior in segment_volume #1209](https://github.com/ivadomed/ivadomed/pull/1209).
>    It works for both CPU and GPU, in ivadomed and in ADS.

I second most of the comments above. Hence, I agree this is the most suitable solution.

**Comment by mariehbourget** [comment]
Thanks @kanishk16 for double-checking this and for the links, they clarify the behavior and will be useful when we move forward with other pytorch versions 🚀.
