### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1213]
## Issue description

Terminal output (from Wandb): [output.log](https://github.com/ivadomed/ivadomed/files/10219808/output.log)

log: [log.log](https://github.com/ivadomed/ivadomed/files/10219815/log.log)

[version_info.log](https://github.com/ivadomed/ivadomed/files/10219790/version_info.log)

<details><summary>Config file</summary>

```console
{
    "command": "train",
    "gpu_ids": [4],
    "path_output": "seg_lesion_output",
    "model_name": "seg_lesion_model",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "wandb": {
        "wandb_api_key": "9095e2bc9e4ab445d478c9c8a81759ae908be8c6",
        "project_name": "basel-mp2rage-lesion",
        "group_name": "my_group",
        "run_name": "run-1",
        "log_grads_every": 100
    },
    "loader_parameters": {
        "path_data": ["/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/data_seg_mp2rage_20221212_175444/data_processed_lesionseg"],
        "subject_selection": {
            "n": [],
            "metadata": [],
            "value": []
        },
        "target_suffix": [["_lesion-manual", "_lesion-manual2"]],
        "extensions": [],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["UNIT1"],
            "testing": ["UNIT1"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": false
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.75,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 4,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 100,
            "early_stopping_patience": 200,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 1e-3,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-3
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "depth": 4,
        "is_2d": false,
        "final_activation": "sigmoid"
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {"binarize_prediction": {"thr": 0.5}},
    "evaluation_parameters": {},
    "transformation": {
        "Resample": {
            "wspace": 1.0,
            "hspace": 1.0,
            "dspace": 1.0
        },
        "CenterCrop": {
            "size": [32, 64, 128]
        },
        "RandomReverse": {
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "RandomAffine": {
            "degrees": 10,
            "scale": [0.2, 0.2, 0.2],
            "translate": [0.2, 0.2, 0.2],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
            "alpha_range": [25.0, 35.0],
            "sigma_range": [3.5, 5.5],
            "p": 0.5,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "RandomGamma": {
            "log_gamma_range": [-1.5, 1.5],
            "p": 0.5,
            "applied_to": ["im"],
            "dataset_type": ["training"]
        },
        "NumpyToTensor": {},
        "NormalizeInstance": {
            "applied_to": ["im"]
        }
    },
    "Modified3DUNet": {
        "applied": true,
        "length_3D": [32, 64, 128],
        "stride_3D": [32, 64, 128],
        "attention": false,
        "n_filters": 8
    }
}
```

</details>

Possibly related to https://github.com/ivadomed/ivadomed/issues/815

**Comment by jcohenadad** [comment]
Running debugging mode, the issue arrives here:

https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L719

Inspecting the variables:
~~~
[angle, axes]
[-0.05377395512467591, [0, 2]]
metadata[MetadataKW.ROTATION] = [angle, axes]
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
~~~

**Comment by jcohenadad** [comment]
Interestingly there is no "str":
~~~
type(angle)
<class 'float'>
type(axes)
<class 'list'>
type(axes[0])
<class 'int'>
type(axes[1])
<class 'int'>
~~~

**Comment by jcohenadad** [comment]
Ah! wait, the error stems from the call to:
~~~
metadata[MetadataKW.ROTATION]
~~~

Because `MetadataKW.ROTATION` is a string.

**Comment by jcohenadad** [comment]
From https://github.com/ivadomed/ivadomed/issues/815, the culprit was the presence of the field "NumpyToTensor" in the data augmentation, which is indeed listed in my original config file (https://github.com/ivadomed/ivadomed/issues/1213#issue-1494577149).

However, I tried with another config file, based on the latest ivadomed version, and I still observe the error. 

<details><summary>More recent config file</summary>

```JSON
{
    "command": "train",
    "gpu_ids": [4],
    "path_output": "model_seg_lesion_mp2rage_",
    "model_name": "model_seg_lesion_mp2rage",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "wandb": {
        "wandb_api_key": "9095e2bc9e4ab445d478c9c8a81759ae908be8c6",
        "project_name": "basel-mp2rage-lesion",
        "group_name": "my_group",
        "run_name": "run-3",
        "log_grads_every": 100
    },
    "loader_parameters": {
        "path_data": ["/Users/julien/temp/model_seg_basel/data_processed_lesionseg_small"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_lesion-manual", "_lesion-manual3"],
        "extensions": [".nii.gz"],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["UNIT1"],
            "testing": ["UNIT1"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false,
        "bids_validate": true
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "split_method" : "participant_id",
        "data_testing": {"data_type": null, "data_value":[]},
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 4,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 50,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-3
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "final_activation": "sigmoid",
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "contrasts",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": true,
        "length_3D": [32, 64, 128],
        "stride_3D": [32, 64, 128],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "hspace": 1,
            "wspace": 1,
            "dspace": 1
        },
        "CenterCrop": {
            "size": [32, 64, 128]},
        "RandomAffine": {
            "degrees": 10,
            "scale": [0.2, 0.2, 0.2],
            "translate": [0.2, 0.2, 0.2],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
			"alpha_range": [28.0, 30.0],
			"sigma_range":  [3.5, 4.5],
			"p": 0.1,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NormalizeInstance": {"applied_to": ["im"]}
    }
}


```

</details>

**Comment by mariehbourget** [comment]
> From #815, the culprit was the presence of the field "NumpyToTensor" in the data augmentation, which is indeed listed in my original config file ([#1213 (comment)](https://github.com/ivadomed/ivadomed/issues/1213#issue-1494577149)).
> 
> However, I tried with another config file, based on the latest ivadomed version, and I still observe the error.

Based on #830, old config file with the "NympyToTensor" key are supposed to be retrocompatible, so I don't think this is the issue here.
Let me test it on my side to reproduce the issue and I'll get back to you asap.

**Comment by mariehbourget** [comment]
As a side note, we should make sure to add a test with the fix so we can catch this in the future.

**Comment by jcohenadad** [comment]
Thank you very much for the excellent detective work @mariehbourget 🙏 . I'm surprised this hasn't been caught before.

**Comment by dyt811** [comment]
Seems like more testing with 3D test pathway will be required. I will make a note to test that part as well in the Loader V2.

**Comment by mariehbourget** [comment]
Ok, I found where this is happening!
The issue is complicated but the fix should be easy.

In short:
* In 3D, the `metadata` variable in [RandomAffine](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L706) is a _list_ of _SampleMetadata_ object and directly cause the error message reported (as mentioned above).
* In 2D, it does not happen because the `metadata` variable is a _SampleMetadata_ object (not a _list_).
* Up until the call for transforms ([here](https://github.com/ivadomed/ivadomed/blob/1528078ce3a5447ef07b53d8f1558113cbe13c70/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py#L220) in 3D and [here](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/loader/mri2d_segmentation_dataset.py#L323) in 2D) the metadata is a _list_.
* Looking closely to data augmentation transforms (ex: [RandomAffine](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L704) or [ElasticTransform](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L883)), many of them have the 2 following wrapper: [multichannel_capable](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L24) and [two_dim_compatible](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L58).
* In [multichannel_capable](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/transforms.py#L24), when the `sample` is a _list_, the metadata is returned as a _SampleMetadata_ object, whereas when the sample is not a list, the metadata is returned "as is" (as a _list_).
* In the call for transforms (again [here](https://github.com/ivadomed/ivadomed/blob/1528078ce3a5447ef07b53d8f1558113cbe13c70/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py#L220) in 3D and [here](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/loader/mri2d_segmentation_dataset.py#L323) in 2D), the `sample` is a _numpy array_ in 3D and a _list_ in 2D
* Conclusion: the difference of _type_ for the `sample` is causing the difference in _type_ for metadata when going through `multichannel capable`.

The bug is _fairly_ recent and was introduced in PR #1169 in July.
* In 3D: when calling the transform [here](https://github.com/ivadomed/ivadomed/blob/1528078ce3a5447ef07b53d8f1558113cbe13c70/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py#L220), `stack_input` is a _numpy array_ (causing the issue) where before it was a _list_ called `seg_pair['input']`.
* In 2D: the equivalent operation is done [here](https://github.com/ivadomed/ivadomed/blob/1528078ce3a5447ef07b53d8f1558113cbe13c70/ivadomed/loader/mri2d_segmentation_dataset.py#L295) where `stack_input` is converted to a _list_ when calling the transform (hence no issue).

As I said, the fix should be simple, but I will require some time to test it properly in different scenarios (2D/3D, single/multi-channel and single/multi-rater).
I should be able to open a PR by the end of the day tomorrow.
