### ISSUE TITLE
Consider renaming `slice_filter_params` and `patch_filter_params`

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1235]
IIUC the difference between the two is that the former applies to training and testing time, while the latter only applies during training time. 

This distinction is not intuitive from the name of the fields.

**Comment by mariehbourget** [comment]
As explained in #1232:

* A **2D slice** is an entire 2D image taken from a 3D volume, ex: an image of size 128x128 taken from a volume of size 128x128x16.
* A **2D patch** is a portion of that entire 2D image, ex: a patch of 32x32 taken from a slice of 128x128.

> IIUC the difference between the two is that the former applies to training and testing time, while the latter only applies during training time.

One of the difference is indeed that patch filter is only applied at training time whereas slice filter is applied at training and testing time. But the 2 kind of filter also don't apply to the same "entity" i.e. a slice vs. a patch.

**Comment by jcohenadad** [comment]
Thank you for the clarification. From the 'patch' vs. 'slice', I now understand better the origin of the field names. However, from the train/test vs. train, it makes little sense. I'm wondering if there is a solution to accommodate both concepts with fields that would be made more intuitive.

**Comment by mariehbourget** [comment]
> I'm wondering if there is a solution to accommodate both concepts with fields that would be made more intuitive.

For some background, I added the "Patch Filter" in PR #980.
My first attempt at the PR was to have a solution that would accommodate both concepts. However, it became really hard to understand/follow really fast and we chose to split the "Slice Filter" and "Patch Filter" in 2 after the first round of review [here](https://github.com/ivadomed/ivadomed/pull/980#issuecomment-1000535086).

Without revisiting it entirely, I am confident that this was the best solution both for implementation and maintenance of the feature.

One of the reason was that a user may want to filter out an empty "slice" from a volume but not filter out an "empty" patch of vice-versa, so having 2 different concepts is helpful and clearer in that case.

Another reason was that the reconstruction algorithm for predictions from 2D patch **need** to have the predictions for all patches, so the "Patch Filter" cannot be applied at testing time.
If I recall correctly, the reconstruction algorithm for predictions of a volume from 2D slices does not have this constraint and therefore the filter can be applied both at training and testing time.

**Comment by jcohenadad** [comment]
Thank you for the additional context, I understand better the decision made, and I agree it does make sense.

Maybe, from a user perspective, it would then be useful to:
- Specify in the "patch filter" section the reason that this filter is not applied during testing (ie: the reconstruction algorithm for predictions from 2D patch needs to have the predictions for **all** patches). Otherwise, the user might think that the distinguishing feature between patch vs. slice filter is the fact that one applies during train/test and the other not, but in fact, this feature is a _consequence_ (not a defining trait).
- cherry on the cake: Consider showing a small sketch of a 3D volume showing a patch (for the patch case) and a slice (for the slice case).
