### ISSUE TITLE
wandb: What is displayed for 3D kernels?

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1247]
### Motivation for the feature

Wandb is great to visualize train/GT inputs, however it shows a 2D window of all patches. Eg: for a batch of 16 it shows this:

![image](https://user-images.githubusercontent.com/2482071/208769581-b3713b31-9d17-42d1-8689-6bf1fc2d8ac9.png)

However, the same visualization happens for 3D models. So I am wondering what is displayed in this case? a randomly selected slice within the 3D patch?  The mid-slice? Something else?

**Comment by naga-karthik** [comment]
The image visualization feature essentially piggybacks off what was previously used for writing the images on tensorboard in the [save_img](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/visualize.py#L132) function. In [these lines](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/visualize.py#L147-L149), we note that for 3D data, the samples from the depth dimension are stacked and visualized. That is, for each depth value, we have a (BxCxHxW) tensor, so B slices of dimensions HxW are visualized. Hence, it is not a randomly selected slice, nor a mid-slice.

**Comment by jcohenadad** [comment]
Yes! You are absolutely right @naga-karthik , thank you for your insight. Wandb _does_ show all the slices in the 3d dimension, but they need to be manually selected using the slider:

![image](https://user-images.githubusercontent.com/2482071/208775785-38ad6b43-e6fe-4487-b545-98539e4b2197.png)

When moving the slider, I recover all slices along the 3rd dimension:

![anim](https://user-images.githubusercontent.com/2482071/208775864-77e81368-a65b-425d-bb70-e00b82551d7e.gif)

**Comment by naga-karthik** [comment]
Hmm, are you sure, it is 16 slices in the depth dimension? I am inclined towards 16 being the _batch size_ (which you mentioned at the top), but since only 8 images are plotted per row, each step gives 16 + 16 + .... until the end of the number of slices in the depth dimension (which might vary depending on the input image). Let me know if it makes sense, or if I am incorrect! 

Note that it does not tell you when the slices for an image end, which is why we see step number in 2500s. So, it must be slices in the depth dimension for all the input images.

**Comment by naga-karthik** [comment]
Ah yes, forgot about the `length_3D` key. 16 is indeed the depth then. Thank you for the clarification!
