### ISSUE TITLE
Force ElasticTransform to be called only on training

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#358]
ElasticTransform doesn't have an undo method which can cause an [error](https://github.com/ivadomed/ivadomed/pull/309#issuecomment-657607855). We should force it to be called only on training or implement an undo method if possible.

**Comment by charleygros** [comment]
Should be caught [here](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/transforms.py#L126).
My guess is that this error is due to #335 not included in PyPi release since I cant reproduce this error with master.

**Comment by andreanne-lemay** [comment]
Ah I see what you mean, but it seems like `ElasticTransform` has attribute `undo_transform` (https://github.com/ivadomed/ivadomed/blob/master/ivadomed/transforms.py#L127), at least on my local computer, it doesn't go through this condition. Probably because it is child of the class `ImedTransform`, so by default the method exists even if it's not implemented?

**Comment by andreanne-lemay** [comment]
As mentioned in my previous comment, removing the [method `undo_transform` of ImetTransform](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/transforms.py#L81) solves the issue.

**Comment by charleygros** [comment]
Yep Zuper :)
Implemented in [95e5a57](https://github.com/ivadomed/ivadomed/pull/309/commits/95e5a57aa62fdbf8b9ca0cfaacd491030958c67f)

My point was that we should not go through this error if the config file is correct (ie Elastic only for training --> undo never called) since #335 is merged. But I agree with you that it's even better with this additional layer of safety.

**Comment by charleygros** [comment]
Closed via #309
