### ISSUE TITLE
Wrong image size while using center crop

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#434]
While working with sct testing large, I cannot use a bigger batch size than one because there is a mismatch in images dimension in the batch. I am using a center crop after a resampling which should be enough to ensure same size images.  As the dimension of the image are really different across the dataset, some needs to be padded and others need to be cropped. 
After a little digging, I think that it comes from the fact that the dimensions are different between what is padded and what is cropped. 
What is really weird is that the difference in dimension at the time of the error was not constant.

**Comment by charleygros** [comment]
Thanks @lrouhier for reporting this.
Could you please share or add in `duke/tmp/` the config file you used to raise this issue? Cheers

**Comment by lrouhier** [comment]
The config file is now in duke/temp/lrouhier/Centercrop_issue, tell me if you have access but I think you should be able to access it. 

I launched two training sequentially, here are the errors I get: 
test 1:
`RuntimeError: stack expects each tensor to be equal size, but got [1, 250, 497] at entry 0 and [1, 250, 502] at entry 1`
test 2: 
`RuntimeError: stack expects each tensor to be equal size, but got [1, 250, 500] at entry 0 and [1, 250, 499] at entry 1`

As you can see what is really weird is that the difference in the size of the images in the batch varies from one training to the other.

**Comment by lrouhier** [comment]
I created a second config file (name config_file_smaller_test.json), with a centercrop with a much smaller size (50x50) and it works, So it appears that if all images are cropped (because they are all bigger than 50x50) there does not seem to be a problem. Maybe it is more of a padding issue. Let me see what happens if I pad all the images.

**Comment by lrouhier** [comment]
Here are some stat about the image: 
min size_x (RL) : 70
max size_x (RL): 71
min size_y (IS): 160
max size_y (IS): 733


I tried to pad only on the first axis (x) with a center crop of size (75,50), it worked. Now If I pad with center crop of size (250,50), I get an error. Same as before the size is not constant. Which means the images have different behavior.

Test 1 failed with different size in batch 249 and 250, 
Test 2 failed with different size in batch 249 and 251 

This is weird.  I will dig around the padding function to see what happens.

**Comment by lrouhier** [comment]
Update: I tried with another dataset (name small_ds in duke/temp/lrouhier/centercrop_issue), which are just extracted subject from sct_testing/large. I cropped some of them to try to recreate the condition and it does seem to work maybe I will need to crop it further (the difference between image is equal to or lower than 15 voxel in a single direction)

**Comment by charleygros** [comment]
> `RuntimeError: stack expects each tensor to be equal size, but got [1, 250, 497] at entry 0 and [1, 250, 502] at entry 1`

I may be very wrong.. but this kind of error does not sound like the error is coming from the cropping or the padding .. but rather from the data itself OR the configuration of the training!
Let me explain: the two dimensions fit (1 and 250) but the third one does not. However.. as far as I understand you are using a 2D network --> so it should not be a problem that the third dimension differs.

What you should have at this point is: XX, XX, 1 (since I saw your images have only one sag slide).
So I am going to look at images headers.

**Comment by charleygros** [comment]
Solved by adding:
```
            "preprocessing": true
```
to `Resample` :-)

Explanation:
You had `preprocessing` for the Cropping but not for the Resampling --> so it was Cropped THEN Resampled which caused the issue you encountered.

**Comment by lrouhier** [comment]
Great catch thanks, i didn't think about that because the order seems right! What about adding a warning in the doc or making postprocessing=True as a default option ?

**Comment by jcohenadad** [comment]
I'm trying to understand the problem in order to help advising. Firstly, I don't find the field "preprocessing" in https://ivadomed.org/en/latest/configuration_file.html#

Am I looking at the right place?

Also, in general, I am not in favour of adding warnings in the doc to avoid that problem. A typical user vaguely glances at the doc to get some specific answers about how the software works, and then spends most of their time coding/debugging. So i'm afraid the warning will be missed (and would make the documentation heavier, if we decide to add warnings for every problem like that). Does it make sense to think of a code-base solution (e.g. having some sort of checker, if some combination of config parameters don't make sense).

**Comment by lrouhier** [comment]
I think that you are. It is an option for the transformation (so that you don't crop your image every epoch for example) so it should be with the transformation explanation. It needs to be added. 

I guess it would make more sense to add a checker than to use the default option I think because other transformations might influence the results depending on the order.

**Comment by charleygros** [comment]
We decided to go with the following code-based solution:
- remove the `preprocessing` parameter
- force `Resample` and `*Crop` to be done only once (ie preprocessing) if they are present in the config file.
- document the fact that these transforms are only performed once, when loading the dataset
- @andreanne-lemay will lead this code change

**Comment by lrouhier** [comment]
closed with #446, avoid future error.
