### ISSUE TITLE
Improve Community Guidelines

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#559]
Currently, Community Guidelines are in:
- https://ivadomed.org/en/latest/contributing.html
- the repository wiki

It would be nice to also
- have a file, eg `CODE_OF_CONDUCT.md` --> only point to the available resources
- have issue and Pull-Request templates pointing to the relevant parts of the wiki

**Comment by joshuacwnewton** [comment]
I wonder if the reviewers meant `CONTRIBUTING.md` instead of `CODE_OF_CONDUCT.md`. Because, `CODE_OF_CONDUCT.md` is more for... standards of behavior? Fostering a welcoming environment through kindness, respect, and handling conflict/discrimination/harassment. For example:  https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md

Code of conducts are lovely, but from context it seems like they meant contributing guidelines, so I'm not sure.

**Comment by joshuacwnewton** [comment]
Assuming they did mean `CONTRIBUTING.md`, then we can [do what SCT does](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/dev_section/CONTRIBUTING.rst).

* Move the `./docs/source/contributing.rst` file to `./CONTRIBUTING.rst` (so that it is visible to reviewers).
* Have the contents of the `./docs/source/contributing.rst` point to the base-level file, e.g. `../../CONTRIBUTING.rst`.

That way, the information is visible in both locations.

**Comment by charleygros** [comment]
> Assuming they did mean `CONTRIBUTING.md`, then we can [do what SCT does](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/dev_section/CONTRIBUTING.rst).
> 
>     * Move the `./docs/source/contributing.rst` file to `./CONTRIBUTING.rst` (so that it is visible to reviewers).
> 
>     * Use a symlink for `./docs/source/contributing.rst` that points to the base-level file.
> 
> 
> That way, the information is visible in both locations.

Makes a lot of sense and sounds great! Thanks @joshuacwnewton for taking care of this
