### ISSUE TITLE
Adapt splitting methods for new loader

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#564]
## Context

This issue is part of the loader refactoring project to include microscopy data (#304) and to migrate to HDF5 loader (#474).

The first step of the refactoring was to generate a bids dataframe: done in #519 and #538 for anat and microscopy data.
The dataframe includes one row per image file from a bids_path (with parsed entities and tsv/json metadata) for each subject and derivatives files, when derivatives are available according to the chosen target suffixes.

The second step is to adapt the splitting methods (train/valid/test) to split using the dataframe.

## Functions to adapt

1. Currently the function [get_new_subject_split](https://github.com/ivadomed/ivadomed/blob/7d3eef70cb24d5a3411927c372e614ced00a140e/ivadomed/loader/utils.py#L96) uses `bids_neuropoly` and `participants.tsv` content to list subjects and metadata. We aim to remove the dependency to bids_neuropoly, and use the metadata already loaded in the dataframe at the previous step.

2. Currently the function [split_dataset](https://github.com/ivadomed/ivadomed/blob/7d3eef70cb24d5a3411927c372e614ced00a140e/ivadomed/loader/utils.py#L34) contains 2 different methods for splitting: `per_patient `and `per_center`.
As discussed previously, for microscopy, we want to implement a `per_sample` method as well, because a same subject can have multiple samples. Ex:
    * sub-01_sample-01_SEM.png
    * sub-01_sample-02_SEM.png

## Next step
Load data as numpy array with different loaders for different file formats.

**Comment by andreanne-lemay** [comment]
Here are some suggestions:

Instead of using hard coded strings (e.g., per_patient, per_center) that we chose arbitrally, the splitting method should refer to a column name in the dataframe. In these cases, `per_patient` would become `participant_id` and `per_center` would become `institution_id`. This way it would automatically adapt to any type of splitting. 

The parameter `center_test` should also be generalized to isolate any data for testing. For instance, we could have something like: `"testing_subjects": {"data_type": "institution_id", "data_value":[ "center_1", "center_2"]} ` or 
`"testing_subjects": {"data_type": "participant_id", "data_value": ["sub-1", "sub-20"]}` or 
`"testing_subjects": {"data_type": "disease", "data_value": ["ms"]}` to keep all ms patients for testing.
