### ISSUE TITLE
Documentation error in virtualenv command

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#574]
### Current behavior

In the RTD [Installation ](https://ivadomed.org/en/stable/installation.html#installation)section, we have the following command:
```
virtualenv venv-ivadomed --python=python3.6
```

### Expected behavior
```
virtualenv venv-ivadomed
```
i.e., be Python version agnostic

**Comment by jcohenadad** [comment]
I suggest reverting the documentation with explicit mention of python's version (could be in brackets), to avoid people installing python2.7 by default.

**Comment by charleygros** [comment]
> I suggest reverting the documentation with explicit mention of python's version (or at least, add a warning), to avoid having people installing python2.7 by default.

Would this [PR](https://github.com/ivadomed/ivadomed/pull/603) address this issue?

**Comment by jcohenadad** [comment]
> Would this PR address this issue?

it does indeed, although i would say it solves it partially. E.g.: someone unfamiliar with virtualenv installs py2.7, runs ivadomed installation, it crashes because of the new requirement https://github.com/ivadomed/ivadomed/pull/603 (which is good!), however, the user being unfamiliar with virtualenv is now wondering: "hum, what should i do then???" --> hence the suggestion to help user with the warning https://github.com/ivadomed/ivadomed/pull/607/files

**Comment by charleygros** [comment]
Yes I agree. So the combination of #603 and #607 should do the job, right? and re-close this issue.
