### ISSUE TITLE
test_segment_volume.py placed under unit_tests instead of functional_tests

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#712]
The testing function `test_segment_volume.py` does test fairly high level stuff (segmentation on a NIfTI image), as such I am wondering why it it not placed under **functional_tests/**?

**Comment by jcohenadad** [comment]
ah, i think i got the logic: "function_tests" is reserved for the CLIs.  Is this good practice @ahill187 @gisellemartel ?  should we rename it "cli_tests" to be more explicit? just a suggestion

**Comment by ahill187** [comment]
I think you're right, if `test_segment_volume.py` is a functional test, we should put it in the functional tests folder. It only has CLI tests in there right now, but I think the distinction of functional/unit tests makes sense.

**Comment by dyt811** [comment]
I think it is okay to keep the `functional_tests` name but we probably should really make it more "functional" and less CLI specific, such as adding `test_segment_volume.py` and other higher level tests there. 

Case in point, I was recently debugging the original [test_automated_training](https://github.com/ivadomed/ivadomed/blob/25dc2f631e8ae8328e6cef09efa452af25f9e698/testing/functional_tests/test_automate_training.py#L33) issue on Windows, and because the original functional test is CLI/script_runner call, I cannot step through the code and debug. So I had to rebuild out the CLI equivalent (which is also high level, i.e. functional) to actually step through the code just to debug. 
![image](https://user-images.githubusercontent.com/6720068/114954445-9a53dd80-9e28-11eb-8a10-254eccdcfd48.png). Functions like this serve similar and actually better debugging purposes than CLI pass/fail testing and should live in the functional_tests for the sanity of the developers. 

I would argue even further actually, we probably should build out not just tests at the cli level but their equivalent underlying equivalent functional call just so it is possible to debug and befitting the existing name "functional_test" more so than "cli_test".
