### ISSUE TITLE
Loader does not support target_suffix when containing nested lists

### ISSUE THREAD

**Issue by gisellemartel** [ivadomed/ivadomed#789]
### Current behavior
As discussed [here](https://github.com/ivadomed/ivadomed/pull/765#pullrequestreview-659363753), the current loader seems to break when we set the `target_suffix` param of loader_params in the config file as a list of lists. For example, having it set like this: `"target_suffix: [["_seg_myelin_manual"], ["_seg_axon_manual"]]"` does not seem to be fully supported. I believe the loader may need to be modified slightly, in addition some unit tests should be added to ensure this functionality is fully supported. 

### Expected behavior
Setting `target_suffix` as a list of lists should be supported by the loader

### Steps to reproduce
Modify the `target_suffix` param of `loader_params` in the config file to be a list of lists rather than a list. Run the training. An error will likely occur and crash the program.

For example, in `config_small.json` initially we have:

`        "target_suffix": ["_seg-manual"],`

Changing it to the following should be supported:

`        "target_suffix": [["_seg-manual"]],`

However, it results in the following error:

```
Annotations from multiple raters will be used during model training, one annotation from one rater randomly selected at each iteration.


ERROR: Please provide only one annotation per class in 'target_suffix' when not training a model.

```

### System description
macOS Catalina 10.15.7 Python 3.8

**Comment by mariehbourget** [comment]
I think the error comes from here in main.
https://github.com/ivadomed/ivadomed/blob/ccd82d22d31ffa53a2d6455ce3a94b97564d624a/ivadomed/main.py#L367
The first parameter or `check_multiple_raters` is `is_train`. https://github.com/ivadomed/ivadomed/blob/ccd82d22d31ffa53a2d6455ce3a94b97564d624a/ivadomed/main.py#L89
Shouldn't we pass `check_multiple_raters(command == "train", loader_params)` instead of `check_multiple_raters(command != "train", loader_params)` to the function?
