### ISSUE TITLE
Ivadomed installation on CC doesn't mention loading of python module or cloning of repo.

### ISSUE THREAD

**Issue by copperwiring** [ivadomed/ivadomed#849]
Ivadomed installation doc (https://ivadomed.org/en/latest/installation.html) has two approaches mentioned. 

**In Approach 2(compatible with Computer Canada (CC)), the first step mentions: ** 
> 
> virtualenv venv-ivadomed
> source venv-ivadomed/bin/activate

However, a new user (new to canada compute), it gives the following error:

`Please load a Python module before running virtualenv.`

![image](https://user-images.githubusercontent.com/23316280/124640047-ba040c00-de41-11eb-860e-74c39cfe8cb7.png)

The step about loading python modules should be added as first step in the installation doc.

**Suggestion:**
First step should be about loading python module with a reference for further details like: https://docs.computecanada.ca/wiki/Utiliser_des_modules/en. It should be followed by an example:

> module load python/3.8

--------------------------------------------------------------------------------------------

**In Approach 2 (compatible with Computer Canada (CC)), the second mentions:** 

> pip install -r requirements.txt

However, there is no mention of cloning the repo which which is where the `requirement.txt` exists. 

**Suggestion**: Hence step to `git clone` the repo should precede the installation from `requirement.txt`

**Comment by jcohenadad** [comment]
> The step about loading python modules should be added as first step in the installation doc.

I would not create a compute-canada-specific documentation because this open source project is directed to the entire planet (not only canadian researchers).  Specific usage for compute canada is already in our internal documentation, especially the part about [loading modules](https://neuropoly.gitbook.io/neuropoly-lab/computing-resources/compute-canada#modules)

**Comment by copperwiring** [comment]
That's a good point @jcohenadad . Thank you for raising it. May be we can just add about `git clone` of the repo. Though it is an obvious step, it will make the steps complete.

**Comment by dyt811** [comment]
> I would not create a compute-canada-specific documentation because this open source project is directed to the entire planet (not only canadian researchers). Specific usage for compute canada is already in our internal documentation, especially the part about [loading modules](https://neuropoly.gitbook.io/neuropoly-lab/computing-resources/compute-canada#modules)

I think we probably should add a link to our Compute Canada specific documentation since we have it handy and so people are aware. 

@copperwiring Good call on `git clone` step.  It was missing because repo cloning wasn't strictly required before we introduced `requirement.txt`/`environment.yml`. Thanks for catching that.

**Comment by copperwiring** [comment]
Thanks @dyt811 . Added this is #851
